{
 "title": "Memcached stats",
 "description": "Prometheus dashboard for memcached services (exporter gitlab.com/theztd/memcached-check)",
 "tags": [
  "prometheus",
  "memcached"
 ],
 "time": { "from": "now-3h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "service",
    "query": {
     "query": "label_values(memcached_up, service)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Connections",
   "type": "stat",
   "gridPos": { "h": 4, "w": 5, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum (memcached_stats{service=\"$service\", type=\"curr_connections\"}) by (instance)",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Commands",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 19, "x": 5, "y": 0 },
   "targets": [
    {
     "expr": "sum (memcached_stats{service=~\"$service\", type=~\"cmd_(.*)\"}) by (type)",
     "legendFormat": "{{command}}"
    }
   ]
  },
  {
   "title": "Memory usage (from the given limit)",
   "type": "stat",
   "gridPos": { "h": 6, "w": 5, "x": 0, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(memcached_stats{type=\"bytes\", service=~\"$service\"}) / sum(memcached_stats{type=\"limit_maxbytes\", service=~\"$service\"})",
     "legendFormat": "% used memory used"
    }
   ]
  },
  {
   "title": "Read / written bytes",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 19, "x": 5, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "irate(memcached_stats{type=\"bytes_written\", service=~\"$service\"}[5m])",
     "legendFormat": "written to network"
    },
    {
     "expr": "- irate(memcached_stats{type=\"bytes_read\", service=~\"$service\"}[5m])",
     "legendFormat": "read from network"
    }
   ]
  },
  {
   "title": "Items in cache",
   "type": "stat",
   "gridPos": { "h": 6, "w": 5, "x": 0, "y": 10 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum (memcached_stats{type=\"curr_items\", service=~\"$service\"})",
     "legendFormat": "items "
    }
   ]
  },
  {
   "title": "GET stats",
   "type": "timeseries",
   "description": "Statistics of GET requests",
   "gridPos": { "h": 8, "w": 19, "x": 5, "y": 14 },
   "targets": [
    {
     "expr": "memcached_stats{type=\"cmd_get\"}",
     "legendFormat": "GET requests"
    },
    {
     "expr": "memcached_stats{type=~\"get_misses\"}",
     "legendFormat": "GET misses"
    },
    {
     "expr": "memcached_stats{type=~\"get_hits\"}",
     "legendFormat": "GET hits"
    },
    {
     "expr": "memcached_stats{type=~\"get_expired\"}",
     "legendFormat": "GET expired"
    }
   ]
  },
  {
   "title": "Bytes in cache",
   "type": "stat",
   "gridPos": { "h": 6, "w": 5, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum (memcached_stats{type=\"bytes\", service=~\"$service\"})",
     "legendFormat": "items "
    }
   ]
  }
 ]
}